### ISSUE TITLE
Fedora 25

### ISSUE THREAD

**Issue by maxandries** [bulletmark/libinput-gestures#42] opened 2016-11-25 14:47 UTC
hey,
I just upgrade from fedora 24 to fedora 25 and it seems it's not working on this version.

**Comment by rickysarraf** [comment] 2016-11-25 17:14
"not working" doesn't help to determine the bug.

You may want to re-read the [README](https://github.com/bulletmark/libinput-gestures/blob/master/README.md) and follow the installation steps again.

**Comment by maxandries** [comment] 2016-11-25 22:25
some of the gestures works, but the pinch does not (and it is configured in the .conf file)

**Comment by bulletmark** [comment] 2016-11-25 22:27
Are you running the very latest version of `libinput-gestures`?

Have you installed `xdotool` and `wmctrl` as per the instructions?

Have you checked the journal, and/or run with the `-v` switch to check what errors are reported?

**Comment by GalaticStryder** [comment] 2016-11-27 00:36
Anything that fallbacks on __xdotool__ will most likely be broken if you're on Fedora 25 using Wayland, which is the "normal" behavior for now.
I've managed to create a local fix for the pinch gestures but it's causing many race conditions with the latest libinput from FreeDesktop. I'll see if I can add the pinch code inside the libinput itself in that case, if @bulletmark approves it of course. I can push it to Fedora's **copr** for testing as well.

**Comment by bulletmark** [comment] 2016-11-27 07:34
@GalaticStryder Are you running the very latest version of libinput-gestures with the default configuration?

Using the latest version, with the default configuration, gives you the following gestures which **work on both Wayland and Xorg**.

- Swipes up/down to change workspace. This works on any desktop (i.e. GNOME, KDE, etc)
- Swipe left/right to go forward/backward in your chrome/firefox browser. Works on any desktop.
- Pinch in/out to enter/exit the GNOME overview.

So please try the current version using the default configuration file and let me know what your comment is about. Arch Linux is a rolling release which changed the default GNOME login to Wayland in early Oct so I have had some time to experiment with this stuff.

**Comment by GalaticStryder** [comment] 2016-11-27 12:48
@bulletmark I can confirm, it works fine on Fedora 25 with Gnome 3.22. I've created a copr repository for Fedora users to install your program: https://copr.fedorainfracloud.org/coprs/galaticstryder/libinput-gestures/
Then they just need to follow the rest of the readme guide to set it up.

**Comment by bulletmark** [comment] 2016-11-27 22:38
@GalaticStryder I have never used Fedora and I don't know spec files but shouldn't the python dependency be stated as python3? Also, those dependencies are all run-time dependencies, not build-time.

**Comment by GalaticStryder** [comment] 2016-11-28 20:30
@bulletmark I've used the libinput spec file to create this one, they just use python there and it works great. I tested the final RPM myself and it's working great that way. I know they are run-time, I've added them to the instructions anyway, next update will add the to run-time.

**Comment by bulletmark** [comment] 2016-11-28 23:52
@GalaticStryder of course the package will work because I understand that F25 includes python 2 and 3 by default. However on Fedora `python` is actually python2 whereas `libinput-gestures` requires python3.

Anyhow, will close this bug because the OP never came back to comment so we can assume it was user error.

**Closed by bulletmark** 2016-11-28 23:52 UTC
