### ISSUE TITLE
Overrides "Disabled touchpad when typing" in Kubuntu 18.04

### ISSUE THREAD

**Issue by mnowotnik** [bulletmark/libinput-gestures#214] opened 2019-05-14 09:26 UTC
Before creating a new issue, please follow each step in the TROUBLESHOOTING section
of the main README.

```
❯ libinput-gestures -l
libinput-gestures: session KDE+x11 on Linux-4.18.0-18-generic-x86_64-with-Ubuntu-18.04-bionic, python 3.6.7, libinput 1.10.4
/usr/bin/libinput-gestures: hash 34ab6c1e45b5673bf2b143a6321c81c4
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         4 xdotool key ctrl+F9
swipe up         3 _internal ws_up
swipe down         _internal ws_down
swipe left         xdotool key alt+Right
swipe right        xdotool key alt+Left
pinch in           xdotool key xdotool key control+minus
pinch out          xdotool key xdotool key control+shift+plus
libinput-gestures: device /dev/input/event17: SYNA2393:00 06CB:7A13 Touchpad
```

**Describe the issue**
Some way of preserving DE touchpad behavior or inactive touchpad timeout setting would be most helpful.

**Comment by bulletmark** [comment] 2019-05-14 09:29
Can you please explain more clearly what you are actually asking for?

**Comment by Mike-Now** [comment] 2019-05-14 12:51
1. Turn on "Disabled touchpad while typing"
2. Turn on libinput-gestures
3. The option "Disabled touchpad while typing" managed by DE does not seem to take effect. Neither does reverse scrolling.

**Comment by bulletmark** [comment] 2019-05-15 00:04
Libinput does palm detection and disable while typing natively, see https://wayland.freedesktop.org/libinput/doc/latest/palm-detection.html so I suggest it should already be working. It works for me.

Also, read the comments about "natural" scrolling in the `libinput-gestures.conf` file. If you want to use the older reverse scrolling direction then merely swap the swipe directions in your configuration.

**Comment by Mike-Now** [comment] 2019-05-15 08:26
I think the problem is Kubuntu does not use Wayland natively and is not compatible with libinput-gestures because of that.

**Comment by Mike-Now** [comment] 2019-05-15 08:31
The bug will probably resolve itself once the Wayland is well supported on Kubuntu:
https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes/Kubuntu#Plasma_Wayland_session_-_Can_be_installed_for_testing.2C_but_is_not_supported_for_18.04

**Comment by bulletmark** [comment] 2019-05-15 09:32
I don't see how you can tell it that "palm detection" and "disable while typing" are not working? As per that link above I reference, they should be enabled by default. `libinput-gestures` only actions the very explicit swipe and pinch movements reported by libinput. All other libinput actions are ignored. You mean to tell me that you occasionally are performing a swipe and seeing that action while you are typing?!

**Comment by Mike-Now** [comment] 2019-05-15 09:40
I don't use wayland so the link about palm detection mentioned above does not apply.
Also, I can clearly tell that touchpad is permanently active after activating libinput-gestures.

**Comment by bulletmark** [comment] 2019-05-15 09:53
libinput is an input device driver for both Wayland and Xorg. The documentation happens to be hosted on the freedesktop wayland site but that functionality is native to the driver so you should not be seeing any accidental `libinput-gestures` actions. You say you can "clearly tell". I repeat - how are you possibly generating an accidental swipe when you are typing?! I just don't see how anybody could accidentally do it. Please be clear about what you mean when you say the "touchpad is permanently active".

**Comment by Mike-Now** [comment] 2019-05-15 10:02
My issue is not with accidental swiping. I don't understand where you would get such an idea.
I touch touchpad lightly while writing. It results in cursor moving to semi-random parts of the screen, buttons being pressed etc. The option "Disabled touchpad when typing" in the Kubuntu touchpad panel prevents it from happening. Using libinput-gestures causes this option to take none, nill, zero effect whatsoever. Please ask if you need further clarifications.

**Comment by bulletmark** [comment] 2019-05-15 10:15
So now I think you are actually suggesting that whenever you run `libinput-gestures` then it breaks the standard Kubuntu "Disable touchpad when typing" setting?! I had no idea that is what you mean't. So please clarify -

1. Type `libinput-gestures-setup autostop` then reboot then confirm that touchpad setting works.
2. Then type `libinput-gestures-setup start` and confirm that setting gets broken?
3. Then type `libinput-gestures-setup stop` and confirm that setting starts working again?

**Comment by Mike-Now** [comment] 2019-05-15 10:55
I'll close it for now as I am unable to replicate it. Maybe the sequence to reproduce is non-obvious or system update changed this behavior. Astonishingly, "reverse scrolling" started to work without any fixes.

**Comment by mnowotnik** [comment] 2019-08-10 12:31
This issue is definitely occurring.
0. Install and enable libinput-gestures 
1. Run `sudo apt update && sudo apt upgrade`
2. Restart computer
3. Natural reverse scrolling and "Disable touchpad when typing" are not working even though they are enabled in settings
4. Run `libinput-gestures-setup stop && libinput-gestures-setup start`
5. Touchpad features are working again

**Comment by bulletmark** [comment] 2019-08-10 23:28
You never did the last tests I asked above. Please remove `libinput-gestures` from your system, reboot, and confirm everything works as you expect. Do that and then come back here.

**Comment by mnowotnik** [comment] 2019-08-11 00:27
I didn't do it, since it is really hard to reproduce this issue and simultaneously pretty easy to make it go away by simple libinput-gestures and user session restart. It seem to manifest itself after software updates. I described the issue, that manifests itself occasionally, perfectly well in the second post.
I advise you to practice reading comprehension ,as it is *really* hard getting through to you and I'm done trying. You can close the issue for all that I care, but be warned that the bug exists.

For the future reader: just execute `libinput-gestures-setup stop` , log out, log in, maybe try turning touchpad settings on and off and finally run `libinput-gestures-setup start`. The touchpad should work as expected now.

**Comment by mnowotnik** [comment] 2019-08-11 00:31
I didn't do it, since it is really hard to reproduce this issue and simultaneously pretty easy to make it go away by simple libinput-gestures and user session restart.

**For the future reader**: just execute `libinput-gestures-setup stop` , log out, log in, maybe try turning touchpad settings on and off and finally run `libinput-gestures-setup start`. The touchpad should work as expected now.

**Comment by bulletmark** [comment] 2019-08-11 02:40
Sorry, but this is the most confusingly described bug I have ever received. Please only reopen it when/if you can describe clearly what the issue is and how it relates to a problem with libinput-gestures.

**Closed by bulletmark** 2019-08-11 02:40 UTC

**Comment by mnowotnik** [comment] 2019-08-12 10:18
On the other hand, this is the bug I spent the most time describing in vain.
Some updates in system software causes touchpad to not work properly when libinput-gestures is active. Is it clear enough?

The bug still persist whether you like it or not. Thankfully, there is a workaround I described above, so the users can circumvent it regardless of the reading comprehension of lack thereof on the side of the maintainer.

**Comment by bulletmark** [comment] 2019-08-12 10:30
You say "Some updates in system software causes touchpad to not work properly when libinput-gestures is active. Is it clear enough?" You opened this bug 3 months ago and only for the first time 2 days ago you mentioned something about system updates via apt-get being the cause of your issue. Is that what you mean by "some updates in system software"? Can't you see how vague that is? Can't you see that updating your system and then rebooting can not be affected by this utility?! Sorry, but you are straight out confused.

**Comment by mnowotnik** [comment] 2019-08-13 07:23
If I knew that update was the reason for this behaviour back then, I would have written it. I only noticed it now, when my touchpad yet again started not working according to settings, because of libinput-gestures being on. But please, call me confused more and ridicule users of your software. This will do wonders.
