### ISSUE TITLE
is my libinput not working properly

### ISSUE THREAD

**Issue by rhoit** [bulletmark/libinput-gestures#22] opened 2016-09-27 18:26 UTC
I'm using Archlinux with the parallel install of synaptic.
My DE is xfce4 with compiz.
my `/etc/X11/xorg.conf.d/30-touchpad.conf` is
```
Section "InputClass"
        Identifier "touchpad"
        Driver "libinput"
        MatchIsTouchpad "on"
        Option "Tapping" "on"
EndSection
```

I looked at the `libinput-debug-events` it shows

"POINTER_MOTION" 1 figure

"POINTER_AXIS"  for 3, 4 .. (any number of fingers)

I'm not sure how check further.

**Comment by bulletmark** [comment] 2016-09-28 00:01
You ask whether libinput is working correctly but you don't state what the problem is?

I am not an expert in the installation of libinput. Why do you need a "parallel install of synaptic". If you remove synaptic and that custom conf (and any other) does your touchpad (and libinput-gestures) work ok?

**Comment by rhoit** [comment] 2016-09-28 03:28
`libinput` works fine for normal operation, but I couldn't get `libinput-gesture` working, just wanted to confirm, thing is did were correct.

![screenshot83](https://cloud.githubusercontent.com/assets/1684754/18899683/87069286-855a-11e6-8cc2-a00532bd9ee5.png)

I installed the `libinput-gesture` from yaourt, I followed instruction provided in the repo's **README** but it showed nothing, when I swiped.

![screenshot85](https://cloud.githubusercontent.com/assets/1684754/18899770/289d52b0-855b-11e6-85a1-f42bcc6af2fb.png)

I didn't removing synaptic completely was following the [archwiki](https://wiki.archlinux.org/index.php/Libinput#Configuration).

I will be removing synaptic and clear all config again today and try again if it works or not.

**Comment by bulletmark** [comment] 2016-09-30 05:52
Sorry but I just noticed you edited your comment above. Github does not notify about comment edits so I did not know you have done anything. Best to add new information as a new comment, particularly when the one comment above now conflicts about whether you have removed synaptic or not. Please clear out everything custom and install/update, i.e.:
~~~~
yaourt -Syau
yaourt -S xf86-input-libinput
yaourt -Rs xf86-input-synaptics
sudo rm /etc/X11/xorg.conf.d/<any-synaptics-or-libinput>.conf
sudo reboot
mv ~/.config/libinput-gestures.conf ~
yaourt -S libinput-gestures
libinput-gestures -d
~~~~

Then let me know if it prints gestures.

**Comment by rhoit** [comment] 2016-10-02 16:19
still nothing..

![screenshot103](https://cloud.githubusercontent.com/assets/1684754/19021921/1376d660-88ec-11e6-9022-64482bbedb65.png)

this is my config file.

https://gist.github.com/dfe7b648afa14a12a45b52debb7c0ba2

**Comment by bulletmark** [comment] 2016-10-02 22:09
If you followed the procedure I gave above then you should have noticed that I asked you to move your personal config file and custom X configuration out of the way because we should first establish that you have installed libinput and this software correctly. After that, run the following to ensure libinput is outputting gesture events:

    libinput-gestures-setup stop
    libinput-gestures -r

**Comment by rhoit** [comment] 2016-10-03 05:22
still nothing here is my xinput thingi.

http://showterm.io/ab0520c26838869e8d8a5

it has libinput-gesture all over it.

when trying `libinput-gesture -r`

http://showterm.io/f4d7bd9861b5116100477

**Comment by bulletmark** [comment] 2016-10-03 08:26
Well clearly libinput is not reporting any gestures for you. However, the problem is beyond this program and is something to do with your setup or touchpad etc so sorry but I will close this bug. I suggest you search the web about libinput and your specific touchpad.

**Closed by bulletmark** 2016-10-03 08:26 UTC

**Comment by rhoit** [comment] 2016-10-03 17:12
Well seems like I have to wait bit for this thing to get fixed, thanks for the great support! :+1:

**Comment by rickysarraf** [comment] 2016-10-03 17:22
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Mon, 2016-10-03 at 10:12 -0700, rho wrote:
> Well seems like I have to wait bit for this thing to get fixed, thanks for the
> great support! 👍

I think I have a similar issue on my other laptop (I'm not sure if it ever
claimed multi touch).

libinput works fairly well on hardware that supports it. If your hardware really
has the capability, then you should report it with libinput upstream.

- -- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJX8pO7AAoJEKY6WKPy4XVp/2YQAJ71rmXiJ0aIATqFaMNmUP4i
0WFmAfTpEGEo/qvIvE+3YHroSM08pBMDsVJe6IA0YhAfnBnkvM85drqufpIgNUmu
kZOmKKi9mIy4AF+CHhGSAYaNoLA/9AdHpYSRJ16XEcnxPPYtsl7Uq3p67/u66kw9
wIgAO3lcLrpjeGb1T6gQVWFoGqJvIiFfURykmZf0Qt843LurgGF4XpZS5x+8Lul5
2Q5MuVA2ipxMnItOh49YMru+E9E8p81XV2uUsTiRg6G7z/vUdenpcDZe1EDTRVgV
m3OMuV0dVLJlN0IOSOBJWajHgt5RXvlPdbAs94DZ9QxTlnimnc02GCrSsBskrlYC
AuxbCBQfGKrnPChnBU8r5ffIV7W+fktEMNlJrZvRdeCpr7RImVVU+3oXxGdSLJq/
Zk7YqsMCayRmxgXcEBWYcUOEx2TUaWHlqEjqfRFrpz5WYAK0qsTzDdzesasW5+sO
7ggIeisDvzWjOHqK3E2m2wteL52kKxKp1JxUmNRx3Xwk9LCPJbHYlwEaTYM6IH+Y
tPd3TMNLyXv8oht/Ty6IpzPb8duD3cWErheGgEJw8qoiii81VCE+0YInt+2MDdpz
T8ZV9YRRX6ybxGLrdGRgzXP0NyV5HvZwW/uycala9uyRpH2IW8iCIXSL/Yd40HrV
7CP11F2vBj6B18xS9sdX
=3Jhw
-----END PGP SIGNATURE-----
