### ISSUE TITLE
Command not started

### ISSUE THREAD

**Issue by antonio-petricca** [bulletmark/libinput-gestures#181] opened 2018-10-12 05:15 UTC
Hi, I am on Linux Mint 19 (Ubuntu 18.04) Mate.

The debug command reports the pinch action as expected, but the commad (xed or any other) won't start.

How could I solve that issue?

Thank you so much!

**Comment by bulletmark** [comment] 2018-10-12 05:18
Note the opening paragraph of the TROUBLESHOOTING section and also the bolded words in step 8. Also note the issue template here. In short, I have tried to make it impossible for new issues to get raised without the user including the output of `libinput-gestures -l` but you have still missed all that prompting :(

**Comment by antonio-petricca** [comment] 2018-10-12 05:43
Sorry, I would provide you more information about the issue.

The **libinput-gestures -l** output is:

> libinput-gestures: session mate+x11 on Linux-4.17.19-041719-generic-x86_64-with-LinuxMint-19-tara, python 3.6.6, libinput 1.10.4, hash 563917528351a9f3d5e4f0780ed4e99c
> Gestures configured in ~/.config/libinput-gestures.conf:
> pinch out        2 xed
> libinput-gestures: device /dev/input/event7: AlpsPS/2 ALPS GlidePoint

The **libinput-gestures -d** is:

> libinput-gestures: PINCH out 2 [10.0, -5.49]
>    xed

The **libinput-gestures -d -r** is:

> libinput-gestures: session mate+x11 on Linux-4.17.19-041719-generic-x86_64-with-LinuxMint-19-tara, python 3.6.6, libinput 1.10.4, hash 563917528351a9f3d5e4f0780ed4e99c
> libinput-gestures: device /dev/input/event7: AlpsPS/2 ALPS GlidePoint
> -event7   DEVICE_ADDED     AlpsPS/2 ALPS GlidePoint          seat0 default group1  cap:pg  size 102x54mm tap(dl off) left scroll-nat scroll-2fg-edge dwt-on
> event7   POINTER_MOTION    +0.64s	 -1.00/ -0.21
> event7   POINTER_MOTION    +0.65s	  0.00/ -0.59
> event7   POINTER_MOTION    +0.68s	  0.21/  0.00
> event7   POINTER_MOTION    +0.69s	  0.79/ -0.56
> event7   POINTER_MOTION    +0.73s	  0.00/  0.27
> event7   POINTER_MOTION    +0.74s	 -1.30/  0.68
> event7   POINTER_MOTION    +0.75s	 -1.08/  0.00
> event7   POINTER_MOTION    +0.76s	 -0.31/  0.66
> event7   POINTER_MOTION    +0.77s	 -0.93/  0.00
> event7   POINTER_MOTION    +0.78s	 -0.26/  0.00
> event7   POINTER_MOTION    +0.80s	  0.00/  0.20
> event7   POINTER_MOTION    +0.81s	  0.00/  0.20
> event7   POINTER_MOTION    +0.82s	  0.00/ -0.20
> event7   POINTER_MOTION    +0.85s	  0.17/ -0.18
> event7   POINTER_MOTION    +0.87s	  0.18/  0.19
> event7   POINTER_MOTION    +0.88s	  0.21/  0.00
> event7   POINTER_MOTION    +0.92s	 -0.16/  0.00
> event7   POINTER_MOTION    +0.94s	  0.00/ -0.15
> event7   POINTER_MOTION    +0.96s	 -0.14/  0.00
> event7   POINTER_MOTION    +0.99s	  0.00/  0.15
> event7   POINTER_MOTION    +1.00s	 -0.15/  0.00
> event7   POINTER_MOTION    +1.05s	  0.00/  0.15
> event7   POINTER_MOTION    +1.06s	  0.00/ -0.17
> event7   POINTER_MOTION    +1.09s	  0.00/  0.17
> event7   POINTER_MOTION    +1.12s	 -0.14/  0.00
> event7   POINTER_MOTION    +1.13s	  0.25/  0.81
> event7   POINTER_MOTION    +1.14s	 -3.64/ -1.53
> event7   POINTER_MOTION    +1.16s	  1.09/  0.77
> event7   POINTER_MOTION    +1.17s	  1.09/  0.77
> event7   POINTER_MOTION    +1.18s	  0.73/  1.53
> event7   POINTER_MOTION    +1.19s	  0.00/  1.14
> event7   POINTER_MOTION    +1.20s	 -0.36/  2.29
> event7   POINTER_MOTION    +1.22s	 -1.09/  3.45
> event7   GESTURE_PINCH_BEGIN  +1.31s	2
> event7   GESTURE_PINCH_UPDATE  +1.31s	2 -0.65/-0.34 (-1.97/-1.04 unaccelerated)  1.11 @  3.85
> event7   GESTURE_PINCH_UPDATE  +1.32s	2  2.12/-6.17 ( 6.40/-18.65 unaccelerated)  1.25 @  1.34
> event7   GESTURE_PINCH_UPDATE  +1.34s	2  3.46/-11.12 ( 9.35/-30.05 unaccelerated)  1.40 @ -0.11
> event7   GESTURE_PINCH_UPDATE  +1.35s	2  3.64/-13.42 ( 9.84/-36.26 unaccelerated)  1.58 @ -0.96
> event7   GESTURE_PINCH_UPDATE  +1.36s	2  0.91/-9.58 ( 2.46/-25.90 unaccelerated)  1.72 @ -1.20
> event7   GESTURE_PINCH_UPDATE  +1.37s	2  1.09/-5.75 ( 2.95/-15.54 unaccelerated)  1.85 @ -0.80
> event7   GESTURE_PINCH_UPDATE  +1.39s	2  4.92/-10.73 (13.29/-29.01 unaccelerated)  1.99 @ -0.56
> event7   GESTURE_PINCH_UPDATE  +1.40s	2  3.10/-9.01 ( 8.37/-24.35 unaccelerated)  2.09 @ -0.56
> event7   GESTURE_PINCH_UPDATE  +1.41s	2 -0.17/ 0.17 (-0.49/ 0.52 unaccelerated)  2.09 @  0.02
> event7   GESTURE_PINCH_UPDATE  +1.45s	2 -0.07/ 0.08 (-0.49/ 0.52 unaccelerated)  2.09 @  0.02
> event7   GESTURE_PINCH_UPDATE  +1.46s	2 -5.85/ 4.79 (-17.72/14.50 unaccelerated)  2.17 @  0.75
> event7   GESTURE_PINCH_UPDATE  +1.47s	2 -6.19/ 1.34 (-16.73/ 3.63 unaccelerated)  2.37 @  1.61
> event7   GESTURE_PINCH_UPDATE  +1.48s	2 -4.01/-1.53 (-10.83/-4.14 unaccelerated)  2.61 @  1.89
> event7   GESTURE_PINCH_UPDATE  +1.49s	2 -6.37/ 3.45 (-17.22/ 9.32 unaccelerated)  2.76 @  0.92
> event7   GESTURE_PINCH_UPDATE  +1.50s	2 -5.28/ 2.68 (-14.27/ 7.25 unaccelerated)  2.84 @ -0.03
> event7   GESTURE_PINCH_UPDATE  +1.52s	2 -2.00/ 2.11 (-5.41/ 5.70 unaccelerated)  2.87 @  0.08
> event7   GESTURE_PINCH_UPDATE  +1.53s	2 -0.55/ 0.38 (-1.48/ 1.04 unaccelerated)  2.88 @  0.04
> event7   GESTURE_PINCH_UPDATE  +1.54s	2  2.19/ 0.77 ( 5.91/ 2.07 unaccelerated)  2.89 @  0.48
> event7   GESTURE_PINCH_UPDATE  +1.70s	2 -4.69/-0.18 (-13.78/-0.52 unaccelerated)  2.86 @ -0.77
> event7   GESTURE_PINCH_UPDATE  +1.72s	2 -11.39/ 2.64 (-33.46/ 7.77 unaccelerated)  2.79 @ -2.52
> event7   GESTURE_PINCH_END  +1.75s	2
> ^CTraceback (most recent call last):
>   File "/usr/bin/libinput-gestures", line 540, in <module>
>     for line in cmd.stdout:
> KeyboardInterrupt

Thank you again!

**Comment by bulletmark** [comment] 2018-10-12 07:21
Using a touchpad gesture to start an editor is not something commonly done. Either way, configuring that command on my system works. Perhaps you don't have your default PATH set up correctly so specify the full path to the command which is a better way to do it anyhow. Also, the way you have configured the command it will run `xed` but will block `libinput-gestures` from running until `xed` terminates and other gestures will get queued up. To avoid this you should create a script e.g. `~/bin/run-xed` which contains:

~~~sh
#!/bin/bash
exec /usr/bin/xed 1</dev/null &>/dev/null &
~~~

Then configure your gesture as `pinch out 2 /home/<user>/bin/run-xed`

**Comment by itsagoodbrain** [comment] 2018-10-17 09:14
I think I'm having similar issues. Hope a variety of issues helps nail down the root cause.

I can run this as a script and it works perfectly where my swiping left changes behaviour depending on if the mouse is over the KDE desktop/taskbar or my mouse is over something else. However when I try to run it with it with libinput-gestures it performs very similarly as above. All debugging info looks as expected, same as above and it appears to be working. 
Even stranger, it seems that sometimes the swipe left ends up successfully working for previousDesktop. The xdotool command however never seems to work.

`#!/bin/bash
point_win_id=$(xdotool getmouselocation --shell | grep -E 'WINDOW' | grep -o '[0-9]*'); 
point_win_class=$(xprop -id $point_win_id WM_CLASS | awk -F '"' '{print(tolower($4));}'); 
[[ $point_win_class == 'plasmashell' ]] && qdbus org.kde.KWin /KWin previousDesktop || xdotool key --window $point_win_id ctrl+Page_Up`

**Comment by bulletmark** [comment] 2018-10-17 09:32
The OP here (@antonio-petricca) never came back and responded so It's reasonable to assume my last comment was correct and his PATH was not set, thus I am going to close this bug.

@itsagoodbrain, your issue is different and what you are essentially asking for is to debug your complicated script. Please follow the TROUBLESHOOTING section and then raise a new bug if you really think something is wrong with `libinput-gestures`.

**Closed by bulletmark** 2018-10-17 09:32 UTC
