### ISSUE TITLE
3 finger gestures stop working after using 4 finger swipe to change workspace

### ISSUE THREAD

**Issue by padok** [bulletmark/libinput-gestures#147] opened 2018-04-25 16:30 UTC
Every time I switch between work-spaces using the 4 finger up/down swipe, the 3 finger gestures stopped working completely.
The only way to get them working again is to switch workplaces many times using the 4 finger gestures or the restart of the service.

I was also able to reproduce the issue on a freshly installed system.

Additional Information:
- ThinkPad T470
- Xorg
- Ubuntu Bionic
    - Linux Idris 4.15.0-19-generic #20-Ubuntu SMP Sun Apr 22 00:03:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- libinput --version
    - 1.10.4
- libinput-gestures -v
    - libinput-gestures: session ubuntu+x11 on Linux-4.15.0-19-generic-x86_64-with-Ubuntu-18.04-bionic, python 3.6.5, libinput 1.10.4
    - libinput-gestures: using ~/.config/libinput-gestures.conf with 5 gestures
    - libinput-gestures: device /dev/input/event5: SynPS/2 Synaptics TouchPad
    - libinput-gestures is already running for louis, terminating ..
- Config
```
Gestures configured in ~/.config/libinput-gestures.conf:
swipe up         4 xdotool key super+Page_Down
swipe down       4 xdotool key super+Page_Up
swipe left       3 xdotool key alt+Right
swipe right      3 xdotool key alt+Left
swipe up         3 xdotool key super+s

```

**Comment by padok** [comment] 2018-04-26 17:29
Sorry, I changed the issue. @bulletmark

**Comment by bulletmark** [comment] 2018-04-27 01:49
Please do step 5 from the TROUBLESHOOTING section. If you see 3 finger gestures stop after doing some 4 finger gestures then the problem is within libinput or your kernel etc.

I note my Arch box has libinput 1.10.5 which is one release later than yours. I see the new release has some fixes for your laptop, see https://lists.freedesktop.org/archives/wayland-devel/2018-April/037934.html although at first hand they don't seem related.

**Comment by padok** [comment] 2018-05-01 15:01
Thanks, it really seems to be my kernel. 
After a 4 finger gesture, only 2 fingers are detected.

**Comment by bulletmark** [comment] 2018-05-02 00:25
Yes, kernel or libinput related. I note that my Arch PC's updated to libinput 1.10.6 today and I see that there are again some minor fixes for Thinkpad T4XX in that release so possibly try to install that yourself.

Anyhow, closing this bug because not related to this utility.

**Closed by bulletmark** 2018-05-02 00:25 UTC

**Comment by tobecci** [comment] 2022-08-01 14:57
I also have this exact issue, how did you later resolve it?

**Comment by bulletmark** [comment] 2022-08-01 20:59
@tobecci, given the conversation above, you should say what laptop you have. Also, please quote the output of `libinput-gestures -l`.

**Comment by tobecci** [comment] 2022-08-01 21:17
Sorry for neglecting to do that, however, I already found something akin to a solution(I worded it this way because I am still getting some occasional  freezes).

this is the libinput issue
https://gitlab.freedesktop.org/libinput/libinput/-/issues/624

**Comment by tobecci** [comment] 2022-08-01 21:24
```txt
➜  ~ libinput-gestures -l
libinput-gestures: session KDE+x11 on Linux-5.15.57-2-MANJARO-x86_64-with-glibc2.35, python 3.10.5, libinput 1.21.0
Hash: 8d8b6a109b84473e049faaf97c63aa33
Gestures configured in ~/.config/libinput-gestures.conf:
swipe left       3 qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut Switch to Previous Desktop
swipe right      3 qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut Switch to Next Desktop
swipe down       3 qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut ShowDesktopGrid
swipe up         3 qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut Expose
swipe up         4 qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut ExposeAll
swipe left       4 qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut Window Close
swipe right      4 qdbus org.kde.kglobalaccel /component/plasmashell org.kde.kglobalaccel.Component.invokeShortcut manage activities
swipe down       4 qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut MinimizeAll
libinput-gestures: device /dev/input/event14: Synaptics TM3385-001
libinput-gestures is installed.
libinput-gestures is set up as a desktop application.
libinput-gestures is currently running as a desktop application.
libinput-gestures is set to autostart as a desktop application.
libinput-gestures is using custom configuration file.
```

PC info
OMEN by HP Laptop 15-ce0xx
Intel i5-7300HQ (4) @ 3.500GHz

**Comment by tobecci** [comment] 2022-08-01 21:28
the solution was to add `psmouse.synaptics_intertouch=1` to the kernel boot parameter
