### ISSUE TITLE
gestures not detected with AlpsPS/2 touchpad

### ISSUE THREAD

**Issue by Dmarc** [bulletmark/libinput-gestures#39] opened 2016-11-21 23:19 UTC
Hi, Thanks for your great work. I was looking something like this for ages.
I've installed libinput-gestures from the Aur on my DELL e7440, running latest gnome-shell 3.22 on Arch, pretty much the same configuration as you. Yet gesture are not detected...
If I run the following command: `libinput-gestures -d`
I get: `libinput-gestures: monitoring device /dev/input/event17 for 0 gestures`.
And if I run the command as root: `sudo libinput-gestures -d`
I get: `libinput-gestures: monitoring device /dev/input/event17 for 6 gestures`,
which is first thing that puzzles me. Most importantly, in both cases swipe and pinch events are not detected.
Any idea of what the problem might be ?

**Comment by bulletmark** [comment] 2016-11-21 23:20
GNOME runs by default on Wayland now, are you running Wayland or Xorg?

**Comment by bulletmark** [comment] 2016-11-21 23:26
Also, you can see that it is reporting 0 gestures so it seems you have created a custom config file but have no entries in it? Delete `~/.config/libinput-gestures.conf` and run it again as your normal user.

**Comment by Dmarc** [comment] 2016-11-22 08:07
There was an empty libinput-gestures.conf indeed (I don't think I created it myself ?!). I deleted it and now libinput-gestures report 6 gestures as normal user too. Thanks for that.

I am running Xorg (I've tried both anyway). I updated to version 2.12 but it is still silently waiting for events while I'm swiping and pinching like hell !

Maybe that helps: if I run `libinput-gestures -r` I have the same sort of following response when I swipe with 2, 3, or 4 fingers:

```
event17	POINTER_AXIS     +28.31s	vert 7.38* horiz -1.69*
event17	POINTER_AXIS     +28.33s	vert 8.49* horiz -1.69*
event17	POINTER_AXIS     +28.35s	vert 8.98* horiz -1.50*
event17	POINTER_AXIS     +28.37s	vert 7.87* horiz -1.12*
event17	POINTER_AXIS     +28.39s	vert 7.75* horiz -0.37*
event17	POINTER_AXIS     +28.41s	vert 8.37* horiz 0.00
event17	POINTER_AXIS     +28.43s	vert 7.50* horiz 0.00
event17	POINTER_AXIS     +28.45s	vert 7.01* horiz 0.00
event17	POINTER_AXIS     +28.47s	vert 6.89* horiz 0.00
```

**Comment by bulletmark** [comment] 2016-11-22 09:15
I get those POINTER_AXIS events if I swipe up or down with 2 fingers (which libinput does not consider a gesture) but I get GESTURE_SWIPE events if I swipe with 3 fingers. Perhaps your touchpad can not report them. Are you running the latest bios update?

Please paste the full output of `libinput-list-devices` here.

BTW, this app never creates or copies the conf file and never has so if you found an empty file then I suggest you created it accidentally as some point.

**Comment by Dmarc** [comment] 2016-11-22 22:54
I thought about bios issue too, so I updated to the last version one week ago, but it did not solve the problem. Also I have a dual boot with Windows and I checked that the gestures are properly detected in Windows. So it seems the touchpad is technically able to recognize multitouch gestures.

Here is the result of `libinput-list-devices`:

```$ libinput-list-devices
Device:           Power Button
Kernel:           /dev/input/event4
Group:            1
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Video Bus
Kernel:           /dev/input/event10
Group:            2
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Power Button
Kernel:           /dev/input/event2
Group:            3
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Sleep Button
Kernel:           /dev/input/event3
Group:            4
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           Laptop_Integrated_Webcam_HD
Kernel:           /dev/input/event11
Group:            5
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           AT Translated Set 2 keyboard
Kernel:           /dev/input/event0
Group:            6
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a

Device:           AlpsPS/2 ALPS DualPoint TouchPad
Kernel:           /dev/input/event17
Group:            7
Seat:             seat0, default
Size:             95.24x43.75mm
Capabilities:     pointer 
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: enabled
Calibration:      n/a
Scroll methods:   *two-finger edge 
Click methods:    none
Disable-w-typing: enabled
Accel profiles:   none
Rotation:         n/a

Device:           AlpsPS/2 ALPS DualPoint Stick
Kernel:           /dev/input/event16
Group:            7
Seat:             seat0, default
Capabilities:     pointer 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      disabled
Nat.scrolling:    disabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *button
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   flat *adaptive
Rotation:         n/a

Device:           Dell WMI hotkeys
Kernel:           /dev/input/event12
Group:            8
Seat:             seat0, default
Capabilities:     keyboard 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      n/a
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   n/a
Rotation:         n/a
```

**Comment by bulletmark** [comment] 2016-11-22 23:13
Either way, if you run `libinput-gestures -r` to see the raw `libinput-debug-events` output for your touchpad and you don't see any GESTURE events then the problem is somewhere with your hardware, the kernel, or libinput. So there is little I can do about it unfortunately.

Is your Arch system completely up to date? It looks like there was a libinput bug fixed for your touchpad around June this year, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823147.

Make sure you have `xf86-input-libinput` installed, and remove any old `xf86-input-synaptics`. Do you also not see the GESTURE events if you log in GNOME using Wayland?

**Comment by Dmarc** [comment] 2016-11-22 23:29
Yes Arch is completely up to date.  `xf86-input-libinput` is installed and `xf86-input-synaptics` is removed. However, `xf86-input-evdev` is still installed. Should I remove it ? I checked that libinput is correctly used to handle the touchpad yet:

```
grep -e "Using input driver " ~/.local/share/xorg/Xorg.0.log
[    15.879] (II) Using input driver 'libinput' for 'Power Button'
[    15.894] (II) Using input driver 'libinput' for 'Video Bus'
[    15.895] (II) Using input driver 'libinput' for 'Power Button'
[    15.896] (II) Using input driver 'libinput' for 'Sleep Button'
[    15.898] (II) Using input driver 'libinput' for 'Laptop_Integrated_Webcam_HD'
[    15.910] (II) Using input driver 'libinput' for 'AT Translated Set 2 keyboard'
[    15.911] (II) Using input driver 'libinput' for 'AlpsPS/2 ALPS DualPoint TouchPad'
[    15.913] (II) Using input driver 'libinput' for 'AlpsPS/2 ALPS DualPoint Stick'
[    15.915] (II) Using input driver 'libinput' for 'Dell WMI hotkeys'
```

**Comment by bulletmark** [comment] 2016-11-22 23:33
`xf86-input-evdev` is required by `xorg-server` so you can't remove it if you want to use Xorg. You didn't answer my question about Wayland?

**Comment by Dmarc** [comment] 2016-11-22 23:37
I rebooted on Wayland. Using `libinput-gestures -r` gives me only POINTER_AXIS events even if I swipe with 3 or 4 fingers.

**Comment by bulletmark** [comment] 2016-11-22 23:39
Note you don't have to reboot to switch between Wayland/Xorg. You just log out, select the other option, and log back in. Anyhow, I will close this bug given the issue is not related to this application.

**Closed by bulletmark** 2016-11-22 23:39 UTC

**Comment by Dmarc** [comment] 2016-11-24 19:54
I reported the bug to libinput: [https://bugs.freedesktop.org/show_bug.cgi?id=98837](url)

**Comment by Creepy-crow** [comment] 2019-10-14 18:04
Hello.
And what should I do when my touchpad detects triple tapping but does not see triple swipe

**Comment by bulletmark** [comment] 2019-10-14 21:26
@Creepy-crow please follow the trouble shooting section in the README and then, if still necessary, raise a new issue describing your problem in detail.
